#!/usr/bin/env python3
"""
PyGubu GUI Düzenleme Rehberi - Pratik Örnekler
"""

def button_positioning_guide():
    """Buton konumlandırma rehberi"""
    print("🎯 BUTON POZİSYON REHBERİ")
    print("=" * 40)
    print()
    print("1. PyGubu Designer'da widget seç")
    print("2. Sağ panelde 'Layout' sekmesi")
    print("3. Grid parametreleri:")
    print("   • row: Satır numarası (0, 1, 2...)")
    print("   • column: Sütun numarası (0, 1, 2...)")
    print("   • sticky: Hizalama (N, S, E, W)")
    print("   • padx: Yatay boşluk")
    print("   • pady: Dikey boşluk")
    print()
    print("ÖRNEK YENİ DÜZEN:")
    print("┌─────────────────────────────┐")
    print("│ [Open File] [Settings]      │  row=0")
    print("│ [Analyze]   [Disassemble]   │  row=1") 
    print("│ [Transpile] [Save All]      │  row=2")
    print("│                             │")
    print("│ File Tree    │ Output       │  row=3")
    print("│             │              │")
    print("└─────────────────────────────┘")

def color_scheme_guide():
    """Renk düzeni rehberi"""
    print("\n🎨 RENK DÜZENİ REHBERİ")
    print("=" * 40)
    print()
    print("KOYU TEMA:")
    print("  • Arka plan: #2b2b2b")
    print("  • Yazı: #ffffff")
    print("  • Butonlar: #404040")
    print("  • Vurgu: #1a73e8")
    print()
    print("AÇIK TEMA:")
    print("  • Arka plan: #f0f0f0")
    print("  • Yazı: #000000")
    print("  • Butonlar: #e0e0e0")
    print("  • Vurgu: #0078d4")

def practical_editing_steps():
    """Pratik düzenleme adımları"""
    print("\n🔧 PRATİK DÜZENLEME ADIMLARI")
    print("=" * 40)
    print()
    print("1. DOSYA AÇ:")
    print("   pygubu-designer")
    print("   File → Open → d64_converter_improved.ui")
    print()
    print("2. BUTON TAŞı:")
    print("   • Sol panelden butonu seç")
    print("   • Layout → row/column değiştir")
    print("   • Preview ile test et")
    print()
    print("3. BOYUT AYARLA:")
    print("   • Widget sekmesi → width/height")
    print("   • Padding → padx/pady")
    print()
    print("4. RENK DEĞİŞTİR:")
    print("   • Widget sekmesi → bg/fg")
    print("   • Font → family/size")
    print()
    print("5. KAYDET VE TEST:")
    print("   • File → Save")
    print("   • Preview → Test Interface")

def widget_hierarchy_guide():
    """Widget hiyerarşi rehberi"""
    print("\n🏗️ WİDGET HİYERARŞİSİ")
    print("=" * 40)
    print()
    print("MEVCUT YAPIMIZ:")
    print("main_window (Toplevel)")
    print("├── toolbar_frame (Frame)")
    print("│   ├── open_file_btn (Button)")
    print("│   ├── settings_btn (Button)")
    print("│   └── save_all_btn (Button)")
    print("├── main_frame (Frame)")
    print("│   ├── analysis_frame (Frame)")
    print("│   │   ├── hybrid_analysis_btn (Button)")
    print("│   │   ├── disassemble_btn (Button)")
    print("│   │   └── transpile_btn (Button)")
    print("│   └── content_frame (Frame)")
    print("│       ├── file_tree (Listbox)")
    print("│       └── disassembly_output (Text)")
    print()
    print("YENİ BUTON EKLEMEK İÇİN:")
    print("• Sağ tık → Add widget → Button")
    print("• Parent frame'i seç")
    print("• Layout ayarlarını yap")

def common_problems_solutions():
    """Yaygın problemler ve çözümler"""
    print("\n🔧 YAYIN PROBLEMLER & ÇÖZÜMLER")
    print("=" * 40)
    print()
    print("PROBLEM: Butonlar üst üste biniyor")
    print("ÇÖZÜM: row/column değerlerini kontrol et")
    print()
    print("PROBLEM: Widget'lar görünmüyor") 
    print("ÇÖZÜM: sticky='nsew' ekle, grid_rowconfigure/columnconfigure ayarla")
    print()
    print("PROBLEM: Renkler değişmiyor")
    print("ÇÖZÜM: Parent frame'in de rengini değiştir")
    print()
    print("PROBLEM: Fontlar çok küçük")
    print("ÇÖZÜM: Widget → font → size artır")
    print()
    print("PROBLEM: Pencere boyutu sabit")
    print("ÇÖZÜM: weight=1 ekle, resizable=True yap")

if __name__ == "__main__":
    button_positioning_guide()
    color_scheme_guide()
    practical_editing_steps()
    widget_hierarchy_guide()
    common_problems_solutions()
    
    print("\n" + "="*50)
    print("🎉 PyGubu ile GUI düzenleme rehberi tamamlandı!")
    print("   Designer'ı açıp pratik yapmaya başlayabilirsiniz!")
    print("="*50)
